In [64]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random

%matplotlib inline
%config InlineBackend.figure_format = 'svg'

### 1

In [9]:
a = np.linspace(12, 23, num=12)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

### 2

In [23]:
b1 = a.reshape(2, 6)
b1

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [24]:
b2 = a.reshape(3, 4)
b2

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [25]:
b3 = a.reshape(4, 3)
b3

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [26]:
b4 = a.reshape(6, 2)
b4

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [27]:
b5 = a.reshape(12, 1)
b5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

In [28]:
format(b5.ndim)

'2'

### 3

In [34]:
c1 = a.reshape(3, -1)
c1

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [35]:
c2 = a.reshape(4, -1)
c2

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [36]:
c3 = a.reshape(6, -1)
c3

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [37]:
c4 = a.reshape(-1, 3)
c4

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [38]:
c5 = a.reshape(-1, 2)
c5

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

### 4

Нет, нельзя

### 5

In [65]:
a = np.random.randn(3, 4)
a

array([[-1.41858644,  1.21096467, -0.4731006 , -0.2067562 ],
       [-1.0628827 , -0.49344752,  0.94097701, -1.62606375],
       [-0.675195  , -0.73650029,  0.1583032 ,  0.16401115]])

In [66]:
a.size

12

In [68]:
format(a.ndim)

'2'

In [74]:
a1 = a.flatten()
a1

array([-1.41858644,  1.21096467, -0.4731006 , -0.2067562 , -1.0628827 ,
       -0.49344752,  0.94097701, -1.62606375, -0.675195  , -0.73650029,
        0.1583032 ,  0.16401115])

In [75]:
a.size == a1.size

True

In [76]:
format(a1.ndim)

'1'

### 6

In [41]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [45]:
format(a.ndim)

'1'

### 7

In [43]:
b1 = np.arange(20, 1, -2)
b = b1.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [44]:
format(b.ndim)

'2'

Разница между массивами a и b в том, что массив a - одномерный, а массив b - двумерный

### 8

In [49]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
v.size

10

### 9

In [56]:
a = np.linspace(0, 11, 12)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [57]:
A = a.reshape(4, 3)
A

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [58]:
At = A.T
At 

array([[ 0.,  3.,  6.,  9.],
       [ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.]])

In [59]:
B = A.dot(At)
B

array([[  5.,  14.,  23.,  32.],
       [ 14.,  50.,  86., 122.],
       [ 23.,  86., 149., 212.],
       [ 32., 122., 212., 302.]])

In [63]:
B.size

16

In [61]:
B.T

array([[  5.,  14.,  23.,  32.],
       [ 14.,  50.,  86., 122.],
       [ 23.,  86., 149., 212.],
       [ 32., 122., 212., 302.]])

Обратная матрица для матрицы B будет равна матрице B

### 10

In [79]:
np.random.seed(42)

### 11

In [134]:
c = np.random.randint(0, 17, 16)
c

array([14,  6, 11,  7, 14,  2, 13, 16,  3,  7,  3,  1,  5,  9,  3, 11])

### 12

In [135]:
C = c.reshape(4, 4)
C

array([[14,  6, 11,  7],
       [14,  2, 13, 16],
       [ 3,  7,  3,  1],
       [ 5,  9,  3, 11]])

In [136]:
D = B + C*10
D

array([[145.,  74., 133., 102.],
       [154.,  70., 216., 282.],
       [ 53., 156., 179., 222.],
       [ 82., 212., 242., 412.]])

In [137]:
d = np.linalg.det(D)
r = np.linalg.matrix_rank(B)
print(f'Определитель матрицы D = {d}')
print(f'Ранг матрицы D = {r}')

Определитель матрицы D = -190799199.99999982
Ранг матрицы D = 2


In [138]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01242416, -0.00433377, -0.01419293,  0.00753808],
       [ 0.00931304, -0.01169565, -0.00188638,  0.00671607],
       [-0.01025686,  0.01083694,  0.02477075, -0.01822555],
       [-0.00124026,  0.00051531, -0.01075434,  0.00817634]])

### 13

In [139]:
for i in range(4):
    for j in range(4):
        if(D_inv[i][j]<0):
            D_inv[i][j] = 0
        else:
            D_inv[i][j] = 1
            
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.]])

In [140]:
E = np.zeros((4, 4))
E

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
for i in range(4):
    for j in range(4):
        if(D_inv[i][j] == 0):
            E[i][j] = C[i][j]
        else:
            E[i][j] = B[i][j]

E

array([[  5.,   6.,  11.,  32.],
       [ 14.,   2.,  13., 122.],
       [  3.,  86., 149.,   1.],
       [  5., 122.,   3., 302.]])