In [1]:
import numpy as np

## Задание 1

In [14]:
a = np.array([[ 1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [15]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

## Задание 2

In [16]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [42]:
a_centered=np.array(a_centered)
v1 = a_centered[:, 0]
v2 = a_centered[:, 1]
a_centered_sp = np.dot(v1, v2)
a_centered_sp

8.0

In [44]:
N = 5 # число наблюдений
b = a_centered_sp/(N-1)
b

2.0

## Задание 4

In [45]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])